version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - nginx-proxy
    environment:
      - DEFAULT_HOST=general.pwm435.space
      - TRUST_DOWNSTREAM_PROXY=true
    labels:
      - com.github.nginx-proxy.nginx

  nginx-proxy-gen:
    image: nginxproxy/docker-gen
    container_name: nginx-proxy-gen
    restart: always
    command: -notify "docker exec nginx-proxy nginx -s reload" -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - ./conf.d:/etc/nginx/conf.d
      - ./templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    networks:
      - nginx-proxy
    depends_on:
      - nginx-proxy
    labels:
      - com.github.nginx-proxy.docker-gen

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    networks:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy-gen
      - DEFAULT_EMAIL=admin@pwm435.space
    depends_on:
      - nginx-proxy
      - nginx-proxy-gen

volumes:
  certs:
    external: true
    name: srv_certs
  vhost:
    external: true
    name: srv_vhost
  html:
    external: true
    name: srv_html
  dhparam:
    external: true
    name: srv_dhparam
  acme:
    external: true
    name: srv_acme

networks:
  nginx-proxy:
    external: true
